### ISSUE TITLE
vmcloak init failed

### ISSUE THREAD

**Issue by Soukaiinaa** [jbremer/vmcloak#101]
Following your guide, i get to this step : 
" vmcloak init --win7x86  --iso-mount win7.ISO --ip [ip]  cuckoo1 " 

giving me back an error: 
Traceback (most recent call last):
  File "/usr/local/bin/vmcloak", line 9, in <module>
    load_entry_point('VMCloak==0.4.3a2', 'console_scripts', 'vmcloak')()
  File "/usr/local/lib/python2.7/dist-packages/click-6.6-py2.7.egg/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click-6.6-py2.7.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click-6.6-py2.7.egg/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click-6.6-py2.7.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click-6.6-py2.7.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/VMCloak-0.4.3a2-py2.7.egg/vmcloak/main.py", line 220, in init
    if not h.buildiso(mount, iso_path, bootstrap, tempdir):
  File "/usr/local/lib/python2.7/dist-packages/VMCloak-0.4.3a2-py2.7.egg/vmcloak/abstract.py", line 247, in buildiso
    copytreelower(mount, outdir)
  File "/usr/local/lib/python2.7/dist-packages/VMCloak-0.4.3a2-py2.7.egg/vmcloak/misc.py", line 50, in copytreelower
    os.path.join(dstdir, path.lower()))
  File "/usr/lib/python2.7/shutil.py", line 84, in copyfile
    copyfileobj(fsrc, fdst)
  File "/usr/lib/python2.7/shutil.py", line 49, in copyfileobj
    buf = fsrc.read(length)
 IOError: [Errno 5] Input/output error

How can i fix this problem? 
Thanks,

**Comment by jbremer** [comment]
Well, is `win7.ISO` a mounted image?

**Comment by Soukaiinaa** [comment]
Yes, it's mounted on this folder :  "  /mnt/win7 "  using this command : 
sudo mount -o loop,ro win7.ISO  /mnt/win7

**Comment by jbremer** [comment]
Then you should pass `/mnt/win7` instead of `win7.ISO` to `vmcloak` ;-)
Perhaps we should do some additional error checking.

**Comment by Soukaiinaa** [comment]
I tried that, but the error is still exist ! :(

**Comment by jbremer** [comment]
Then your ISO is most likely corrupt, try re-downloading it or another one.

**Comment by Soukaiinaa** [comment]
I tried to install manually windows7 with the same ISO, and it worked well

**Comment by pawayf** [comment]
I got this error when mounting the iso with a non-root user.
