### ISSUE TITLE
Office Installation Error

### ISSUE THREAD

**Issue by scrublullz** [jbremer/vmcloak#113]
I am running into issues installing either Office 2007 or 2010. 

I verified that all Python packages are up-to-date.

Error text:
```
$ vmcloak install Win7Ent01 office office.isopath=/data00/isos/office2010sp2x64.iso office.serialkey=SERIAL-KEY-OFFICE
Traceback (most recent call last):
  File "/usr/local/bin/vmcloak", line 9, in <module>
    load_entry_point('VMCloak==0.4.4a2', 'console_scripts', 'vmcloak')()
  File "/usr/local/lib/python2.7/dist-packages/click-6.6-py2.7.egg/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click-6.6-py2.7.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click-6.6-py2.7.egg/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click-6.6-py2.7.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click-6.6-py2.7.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/VMCloak-0.4.4a2-py2.7.egg/vmcloak/main.py", line 352, in install
    d(h, m, a, image, version, settings).run()
  File "/usr/local/lib/python2.7/dist-packages/VMCloak-0.4.4a2-py2.7.egg/vmcloak/dependencies/office.py", line 55, in run
    config % dict(serial_key=self.serialkey, activate=self.activate)
  File "/usr/local/lib/python2.7/dist-packages/VMCloak-0.4.4a2-py2.7.egg/vmcloak/agent.py", line 123, in upload
    contents = io.BytesIO(contents)
TypeError: 'unicode' does not have the buffer interface
```

**Comment by razuz** [comment]
just bumped into this case myself
introduced with https://github.com/jbremer/vmcloak/commit/06fe613c6f0e5314776eea2b403825bea8464829#diff-6dbf20362e92cf9397e7ef393e82cddaR123

**Comment by jbremer** [comment]
@scrublullz this has been resolved thanks to @razuz. Will be releasing this as part of the next vmcloak release! Thanks for the bug report.

**Comment by jbremer** [comment]
You can now find `vmcloak==0.4.4` which includes the fix for this issue!
