### ISSUE TITLE
The VM has terminated unexpectedly during startup because of signal 6

### ISSUE THREAD

**Issue by ssabetan** [jbremer/vmcloak#133]
Hi all,
I am trying to boot up my VM using vmcloak modify to make some manual changes. I'm getting the error below. This is a fresh vmcloak install on a fresh Ubuntu 16.04. Any ideas? Thanks.

```
user@user16:~$ vmcloak init --win7x64 Win7
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
user@user16:~$ vmcloak install Win7 adobe9 wic pillow dotnet40 java7
ERROR:vmcloak:You specified wic. Will be reinstalling as: wic
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
user@user16:~$ vmcloak modify Win7 --vm-visible
VBoxManage: error: The virtual machine 'Win7' has terminated unexpectedly during startup because of signal 6
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine
ERROR:vmcloak.vm:[-] Error running command: Command '['/usr/bin/VBoxManage', 'startvm', u'Win7', '--type', 'gui']' returned non-zero exit status 1
Traceback (most recent call last):
  File "/usr/local/bin/vmcloak", line 9, in <module>
    load_entry_point('VMCloak==0.4.5', 'console_scripts', 'vmcloak')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/vmcloak/main.py", line 426, in modify
    m.start_vm(visible=vm_visible)
  File "/usr/local/lib/python2.7/dist-packages/vmcloak/vm.py", line 200, in start_vm
    type_="gui" if visible else "headless")
  File "/usr/local/lib/python2.7/dist-packages/vmcloak/vm.py", line 40, in _call
    raise CommandError
vmcloak.exceptions.CommandError
user@user16:~$

**Comment by samwakel** [comment]
Try running the VM without the --vm-visible option. You can then open VirtualBox manually, highlight the VM and click "show" (normally where start is in VBox) to get a GUI to interact with it.

The error you're getting there is from Virtualbox, not VMCloak, however VMCloak throws an exception as VirtualBox exits with an error code.
