### ISSUE TITLE
Cannot assign requested address

### ISSUE THREAD

**Issue by jhg** [jbremer/vmcloak#31]
```python
INFO:vmcloak:Waiting for the Virtual Machine 'w7' to connect back, this may take up to 30 minutes.
Traceback (most recent call last):
  File "/usr/local/bin/vmcloak", line 301, in <module>
    main()
  File "/usr/local/bin/vmcloak", line 240, in main
    sock.bind((s.host_ip, s.host_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address
```

This error is in less of 30 min.

**Comment by jhg** [comment]
My fail, I don't understand well `--hostonly-ip` and `--host-ip` with only first option work, with both fail. @jbremer can close this, please.
