### ISSUE TITLE
crash during snapshot

### ISSUE THREAD

**Issue by razuz** [jbremer/vmcloak#44]
Hi,

while creating a snapshot with latest version I bumped into a case like this. Running on clean install of ubuntu and Virtualbox 5.0.16-105871~Ubuntu~trusty amd64

-----
![snapshot](https://cloud.githubusercontent.com/assets/12982458/14583246/ada56d20-0424-11e6-8bdd-b2c0a58be6b8.png)
-----

error from console :
------
razu@razu:~$ vmcloak snapshot --vm-visible win7p1 win764bit 192.168.56.101
Traceback (most recent call last):
  File "/usr/local/bin/vmcloak-snapshot", line 5, in <module>
    pkg_resources.run_script('VMCloak==0.3.10', 'vmcloak-snapshot')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/VMCloak-0.3.10-py2.7.egg/EGG-INFO/scripts/vmcloak-snapshot", line 95, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/VMCloak-0.3.10-py2.7.egg/EGG-INFO/scripts/vmcloak-snapshot", line 82, in main
    a.static_ip(args.ipaddr, image.netmask, image.gateway)
  File "/usr/local/lib/python2.7/dist-packages/VMCloak-0.3.10-py2.7.egg/vmcloak/agent.py", line 85, in static_ip
    except requests.exceptions.ReadTimeout:
AttributeError: 'module' object has no attribute 'ReadTimeout'

**Comment by jbremer** [comment]
Please upgrade your version of `requests` (`pip install -U requests`) ;-)

**Comment by razuz** [comment]
:) that indeed solved this issue ... OS had control over the pack :/
