### ISSUE TITLE
has no attribute startswith

### ISSUE THREAD

**Issue by lab313ru** [jbremer/vmcloak#54]
```
user@localhost ~ $ vmcloak init --win7 seven0
Traceback (most recent call last):
  File "/usr/local/bin/vmcloak-init", line 5, in <module>
    pkg_resources.run_script('VMCloak==0.3.11', 'vmcloak-init')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/VMCloak-0.3.11-py2.7.egg/EGG-INFO/scripts/vmcloak-init", line 161, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/VMCloak-0.3.11-py2.7.egg/EGG-INFO/scripts/vmcloak-init", line 65, in main
    h = Windows7x86()
  File "/usr/local/lib/python2.7/dist-packages/VMCloak-0.3.11-py2.7.egg/vmcloak/abstract.py", line 183, in __init__
    self.path = os.path.join(self.data_path, self.name)
  File "/usr/lib/python2.7/posixpath.py", line 75, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'

```

**Comment by jbremer** [comment]
Please upgrade to the latest version and let me know if that fixes anything :-)

**Comment by lab313ru** [comment]
This what I have with the current version in your git.

**Comment by jbremer** [comment]
Right, I'm sorry, I was under the impression for a second that the latest version was `0.3.14` or so.
Should be fixed now. Thanks!
