### ISSUE TITLE
ImportError: cannot import name OperatingSystem

### ISSUE THREAD

**Issue by housemusic42** [jbremer/vmcloak#76]
hello,

trying out this awesomeness but running into an issue building the VM.
 ran through the blog and mounted the iso
```
bullwinkle@woody:~/isos$ mount -l | grep win7
/home/bullwinkle/winsp.iso on /mnt/win7 type iso9660 (ro) [WINSP]

bullwinkle@woody:~/isos$ df -aTh | grep win7
/dev/loop0     iso9660          2.4G  2.4G     0 100% /mnt/win7

 
```
then i run the commands and get the python error

```
vmcloak init win7x64 seven0

Traceback (most recent call last):
 File "/usr/local/bin/vmcloak-init", line 12, in <module>
 from vmcloak.dependencies import Python27
File "/usr/local/lib/python2.7/dist-packages/vmcloak/dependencies/__init__.py", line 5, in <module>
 from vmcloak.abstract import Dependency
File "/usr/local/lib/python2.7/dist-packages/vmcloak/abstract.py", line 6, in <module>
import os.path
File "/usr/local/lib/python2.7/dist-packages/vmcloak/os/__init__.py", line 5, in <module>
 from vmcloak.os.winxp import WindowsXP
File "/usr/local/lib/python2.7/dist-packages/vmcloak/os/winxp.py", line 9, in <module>
 from vmcloak.abstract import OperatingSystem
ImportError: cannot import name OperatingSystem

```

any clues to what i might be running into? i'll keep poking away but thanks!

```
bullwinkle@woody:~/isos$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
Linux woody 3.16.0-77-generic #99~14.04.1-Ubuntu SMP Tue Jun 28 19:17:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by razuz** [comment]
@housemusic42 
you're missing -- in front of win7x64, but that should also work  : 
`vmcloak init --win7x64 seven0 --iso-mount /mnt/win7/`

**Comment by housemusic42** [comment]
yup - that isomount got it working. i apologize, it wasn't apparent i needed that! i'll look harder next time.

**Comment by jbremer** [comment]
Really, that solved it? It looks more like a package issue to me, actually.
See also the output for me.

```bash
$ vmcloak init win7x64 seven0
Usage: vmcloak init [OPTIONS] NAME

Error: Got unexpected extra argument (seven0)
```
